# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d16f3c482849a9f2d5adacf8e889bd25aa857252e2ce28d93bebab2abc4048451f9d731d662084256976ec9f7e588c26e6cc4c0c2567b421843538071e328343

test:
  secret_key_base: 5a9b31817d11024837568bfaa56f1ff1b6d7f5782ec8bba9fd7a094ff5450487243b32fa3802072f3742cbbb8ed9c7c9a9c8b7b6f5408554e861de9e4b100571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
